name: HSBC PreInterview - Jmeter CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JMeter
        run: |
          JMETER_VERSION=5.6.2

          # Remove any previous JMeter folder
          rm -rf jmeter
          rm -rf apache-jmeter-$JMETER_VERSION
      
          # Download and extract
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xzf apache-jmeter-$JMETER_VERSION.tgz
      
          # Rename extracted folder
          mv apache-jmeter-$JMETER_VERSION jmeter
      
          # Verify installation
          ls -la jmeter/bin

      - name: Run JMeter Test
        run: |
          ./jmeter/bin/jmeter \
            -n \
            -t tests/json_holder_public_apis_ci.jmx \
            -l results/results.jtl \
            -e \
            -o results/dashboard      
            
          EOF
          
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results
